In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4]
type(list1)


list

In [3]:
arr=np.array(list1)
print(arr)

[1 2 3 4]


In [4]:
type(arr)

numpy.ndarray

In [7]:
arr2=np.array([[1,2,3,4],
            [5,6,7,8]
            ])

In [8]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr3=np.array([[ 
    [1,2,3],
    [3,4,5],
    [7,8,9]
],
               [
                   [1,2,3],
    [3,4,5],
    [7,8,9]]
                   
               ])
print(arr3)
    

[[[1 2 3]
  [3 4 5]
  [7 8 9]]

 [[1 2 3]
  [3 4 5]
  [7 8 9]]]


In [23]:
arr4=np.zeros((5,4,3))
print(arr4)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
arr4=np.ones((5,4,3))
print(arr4)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
arr5=np.arange(0,20)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
arr6=np.linspace(1,10,5)
print(arr6)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
arr6.shape

(5,)

In [20]:
arr4.shape

(5, 4, 3)

In [26]:
arr5.size

20

In [27]:
arr5.ndim

1

In [28]:
arr4.ndim

3